version: '3.4'

services:
  myosshours.backend.rest:
    image: ${DOCKER_REGISTRY-}myosshoursbackendrest
    build:
      context: .
      dockerfile: MyOssHours.Backend.REST/Dockerfile
    ports:
    - 6003:6003
    extra_hosts:
    - "host.docker.internal:host-gateway"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "11433:1433"